---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-server
  labels:
    app: springboot-server
  namespace: springboot-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-server
  template:
    metadata:
      labels:
        app: springboot-server
    spec:
      containers:
      - name: springboot-server
        image: 843100585464.dkr.ecr.us-east-2.amazonaws.com/ice-raven-springboot:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-server
  labels:
    app: springboot-server
  namespace: springboot-server
spec:
  type: NodePort
  selector:
    app: springboot-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080